[project]
name = "chat-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.122.0",
    "openai>=2.8.1",
    "slowapi>=0.1.9",
    "uvicorn>=0.38.0",
]
